Merge master to develop
kovinz/BigQueryEstates pull request #1
Opened 2020-05-19 13:11 UTC by kovinz

2020-05-19 14:42 UTC, vasidzius commented on src/main/java/bigqueryestatespring/controllers/EstatesController.java
> +        Service service = new EstatesService();
это кандидат на dependency injection. Попробуй перевести service в поле контроллера и сделать EstateService бином - повестить на него @Service

2020-05-19 15:51 UTC, Stranger65536 requested changes

2020-05-19 15:51 UTC, Stranger65536 commented on src/main/java/bigqueryestatespring/controllers/EstatesController.java
> +        if (top == null) {
what if both params are valid and negative?

2020-05-19 15:51 UTC, Stranger65536 commented on src/main/java/bigqueryestatespring/controllers/EstatesController.java
> +    public final ResponseEntity<Exception> handleAllExceptions(RuntimeException ex) {
what if non-runtime sneaky exception is thrown?

2020-05-19 15:51 UTC, Stranger65536 commented on src/main/java/bigqueryestatespring/services/EstatesService.java
> +            return BigQueryOptions.newBuilder()
make credentials as bean, this service as bean as well and use DI

2020-05-19 15:51 UTC, Stranger65536 commented on src/main/java/bigqueryestatespring/services/EstatesService.java
> +    private QueryJobConfiguration getQueryJobConfiguration(int bottom, int top) {
is there any better way to generate such query? 
You can start with query template with substitutions (beware of SQL injection)
or use jook

```
// Fetch a SQL string from a jOOQ Query in order to manually execute it with another tool.
// For simplicity reasons, we're using the API to construct case-insensitive object references, here.
Query query = create.select(field("BOOK.TITLE"), field("AUTHOR.FIRST_NAME"), field("AUTHOR.LAST_NAME"))
                    .from(table("BOOK"))
                    .join(table("AUTHOR"))
                    .on(field("BOOK.AUTHOR_ID").eq(field("AUTHOR.ID")))
                    .where(field("BOOK.PUBLISHED_IN").eq(1948));
String sql = query.getSQL();
```

2020-05-19 15:51 UTC, Stranger65536 commented on src/main/java/bigqueryestatespring/services/EstatesService.java
> +    private TableResult getTableResultOfEstates(int bottom, int top) {
Big Query has some limitations of concurrent jobs running.
Can you use thread pool and use future here?

2020-05-19 15:51 UTC, Stranger65536 commented on src/main/java/bigqueryestatespring/services/EstatesService.java
> +            ObjectMapper mapper = new ObjectMapper();
object mapper is thread-safe, use can use it globally

2020-05-19 15:54 UTC, vasidzius commented on src/main/java/bigqueryestatespring/exceptionMessages/ExceptionMessage.java
> +    String EXCEPTION_WHILE_CREATE_JSON = "Exception happened while creating json";
есть конвенция которая гласит что static final переменные называются с помощью upper case. ПРосмотри пож-та весь код и все переменные, которые у тебя upper case либо повесь модификаторы static final, либо переименуй в lower case. Например здесь однозначно все строки должны быть public static final

2020-05-19 15:54 UTC, vasidzius commented on src/main/java/bigqueryestatespring/services/EstatesService.java
> +    private List<String> columnNames = Arrays.asList(OPERATION, PROPERTY_TYPE, COUNTRY_NAME, STATE_NAME);
есть ли серьезная необхожимость держать state в поле? когда у тебя запросы менеджит http сервер окей, он сам все заизолирует и запустит в разных потоках. Но вот кто-то решил что твой код на столько хорош, что взял твой модуль и подрубил в свой код. с этого момента появляется уязвимость no thread safe. Этот кодер может случайно переиспользовать один и тот же EstatesService и все посыпется.

Попробуй состояние, которое отностися только к одному запросу, перенедавать через параметры методов. 

В идеале все сервисы должны быть state less

2020-05-19 15:54 UTC, vasidzius commented on src/main/java/bigqueryestatespring/services/EstatesService.java
> +    public EstatesService(List<String> columnNames) {
не нашел использования. Если код не юзается, удаляй

2020-05-19 15:54 UTC, vasidzius commented on src/main/java/bigqueryestatespring/services/EstatesService.java
> +    private BigQuery getBigQueryInstance() {
прям из названия видно что это кандидат на бин - @Component BigQueryService. Вынеси его, а сейчас на каждый запрос создается новый. Добавь к нему lazy initialization

2020-05-19 15:54 UTC, vasidzius commented on src/main/java/bigqueryestatespring/services/EstatesService.java
> +                .append(") ");
минорный доеб. Здесь такое ок, но если бы у тебя был бы сервис с многими запросами и запросы были бы 100500 строчные, то такой подход читался бы тяжело. КЛассно было бы вынести описание запроса в отдельный файл с переменными, которые бы подставлялись во время рантайма. Типа как скрипт

2020-05-19 15:54 UTC, vasidzius commented on src/main/java/bigqueryestatespring/services/EstatesService.java
> +            throw new RuntimeException(ex.getMessage());
не очень красиво. Ты бросаешь и сам тут же ловишь чтобы опять бросить. при этом у тебя есть @ExceptionHandler в котроллере, который и сам может отловить экспешены. Попробуй выцепить лишние перехваты и убрать их.  Попробуй заменить RuntimeException на свои, более осмысленные экспешены.

2020-05-19 15:54 UTC, vasidzius commented on src/main/java/bigqueryestatespring/services/EstatesService.java
> +            ex.printStackTrace();
ты разделяешь экспшены, но в итоге просто их стек трейсишь, что моветон. Добавь пожалуйста логирование. Если раскуршиь как логи выводить не только в stdout но еще и созранять в какой ниб файл, будет вообще огонь
LOGGER.error('....')

2020-05-19 15:54 UTC, vasidzius commented on src/main/java/bigqueryestatespring/services/EstatesService.java
> +            throw new RuntimeException(TABLE_RESULT_IS_NULL);
как будто не возможна ситуация что tableResul null. Мож я не понял, но вроде ты все раньше отловил, не?

2020-05-19 15:54 UTC, vasidzius commented on src/main/java/bigqueryestatespring/services/EstatesService.java
> +    private void createBranch(NodeWithChildren current, FieldValueList row) {
как будто это самая главная логика. и на нее должен быть юнит тест

2020-05-19 15:54 UTC, vasidzius commented on src/main/java/bigqueryestatespring/services/EstatesService.java
> +            ObjectMapper mapper = new ObjectMapper();
это достаточно тяжелый объект, он всегда есть дефолтовый в Spring Web. Можно заавтовайрить когда перепишешь сервис на бин

2020-05-22 09:24 UTC, vasidzius commented
approve

2020-05-22 15:25 UTC, merged